[package]
name = "credit_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.5"
rand = "0.8.0"

[dev-dependencies]
assert-impl = "0.1.3"
assert_matches = "1.5.0"